---
title: "Taxa"
author: "Haipeng Sun"
date: "8/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## library
```{r message=FALSE, warning=FALSE, include=FALSE}
library(phyloseq)
library(Hmisc)
library(agricolae)
library(grid)
library(gridExtra)
library(gtable)
library(ggrepel)
library(phyloseq)
library(usedist)
library(purrr)
library(furrr)
library(rlist)
library(ggpubr)
library(ggtext)
library(glue)
library(gplots)
#library(ggpattern)
#library(UpSetR)
library(RColorBrewer)
#library(randomcoloR)
library(patchwork)
library(ComplexHeatmap)
library(tidyverse)
```

## load data
```{r}
load(file = "~/Library/CloudStorage/Dropbox/Rutgers/20220606_RUN41_milk/Data/phylo_meta.Rdata")
temp_out = "~/Library/CloudStorage/Dropbox/rutgers/20220606_RUN41_milk/Data/output/taxa/"
```

## Global samples
```{r eval=FALSE, include=TRUE}
# meta_global <- phylo_decontam_clean_rf@sam_data@.Data %>% as.data.frame()
# names(meta_global) <- phylo_decontam_clean_rf@sam_data@names
# meta_global$SampleID <- phylo_decontam_clean_rf@sam_data@row.names
# meta_global <- rbind(meta_global %>% filter(!is.na(Country), Project %in% c("Global", "Upside", "Milkbank")),
#                      #meta_global %>% filter(!is.na(Country), Project  %in% c("Covid Mom", "Family", "PR")) %>%
#                      meta_global %>% filter(!is.na(Country), Project=="PR") %>%
#                filter(TimePoint == 1200))
# 
# phylo_global <- prune_samples(meta_global$SampleID, phylo_decontam_clean_rf)
# phylo_global_s <- tax_glom(phylo_global, taxrank = "Species", NArm=FALSE)
# phylo_global_g <- tax_glom(phylo_global, taxrank = "Genus", NArm=FALSE)
# phylo_global_f <- tax_glom(phylo_global, taxrank = "Family", NArm=FALSE)
# phylo_global_p <- tax_glom(phylo_global, taxrank = "Phylum", NArm=FALSE)

#save(meta_global, phylo_global, phylo_global_s, phylo_global_g, phylo_global_f,phylo_global_p,
#     file = "~/Dropbox/Rutgers/20220606_RUN41_milk/Data/phylo_global.Rdata")
load(file = "~/Dropbox/Rutgers/20220606_RUN41_milk/Data/phylo_global.Rdata")
#rm(phylo_all, phylo_decontam, phylo_decontam_clean, phylo_decontam_clean_rf)

comp_kw_aov = function(wdat, x, y){
  #input data, respond variable y, categorize variable x
  require(agricolae)
  ktest1 = kruskal(wdat[y], wdat[x], alpha = 0.05, p.adj="none", group=T, main = "wdat", console=FALSE)
  out_g_1 = ktest1$groups %>% rownames_to_column(var = "Var") %>% dplyr::select(Var, groups) %>% rename(KW_group = groups)
  ktest2 = kruskal(wdat[y], wdat[x], alpha = 0.05, p.adj="none", group=F, main = "wdat", console=FALSE)
  out_c_1 = ktest2$comparison %>% rownames_to_column(var = "comp") %>% dplyr::select(comp, pvalue) %>% rename(KW_pvalue = pvalue)
  fit = aov(as.formula(paste0(y, "~", x)), wdat)
  tukey1 = HSD.test(fit, x, group = T)
  out_g_2 = tukey1$groups %>% rownames_to_column(var = "Var") %>% dplyr::select(Var, groups) %>% rename(aov_group = groups)
  tukey2 = HSD.test(fit, x, group = F)
  out_c_2 = tukey2$comparison %>% rownames_to_column(var = "comp") %>% dplyr::select(comp, pvalue) %>% rename(aov_pvalue = pvalue)
  out_g = merge(out_g_1, out_g_2,by = 1)
  out_c = merge(out_c_1, out_c_2,by = 1)
  res = list(out_g, out_c)
  names(res) = c("grp","comp")
  res
}
 
my_summarize = function(x){
  data.frame(
             N = n(),
             Min = min(x,na.rm = T),
             Q5 = quantile(x, probs = 0.05, na.rm = T),
             Q10 = quantile(x, probs = 0.1, na.rm = T),
             Q25 = quantile(x, probs = 0.25, na.rm = T),
             Med = median(x, na.rm = T),
             Mean = mean(x, na.rm = T),
             Q75 = quantile(x, probs = 0.75, na.rm = T),
             Q95 = quantile(x, probs = 0.95, na.rm = T),
             Max = max(x,na.rm = T)
             )
}
```

## unique ASV/species/genus in different Country (Global Project)
```{r}
for (taxrank in c("ASV","Species","Genus", "Family")){
  if (taxrank == "ASV"){
    ft <- otu_table(phylo_global@otu_table) %>% as.data.frame() %>% t()
  }else if(taxrank == "Species"){
    ft <- otu_table(phylo_global_s@otu_table) %>% as.data.frame() %>% t()
  }else if(taxrank == "Genus"){
    ft <- otu_table(phylo_global_g@otu_table) %>% as.data.frame() %>% t()
  }else{
    ft <- otu_table(phylo_global_f@otu_table) %>% as.data.frame() %>% t()
  }
  ft <- ft[meta_global$SampleID,]
  asv_sum_country <- aggregate(ft, by = list(meta_global$Country), sum)
  asv_sum_country_lst <- split(asv_sum_country[,-1], asv_sum_country[,1])
  asv_lst <- lapply(asv_sum_country_lst, function(dat){
    names(dat)[(which(dat[1,] > 1))]
  })
  g <- upset(fromList(asv_lst), 
           sets = c("Equatorial Guinea", "Kenya", "Senegal", "South Sudan", "Tanzania",
                    "Ecuador", "ElSalvador", "Mexico", "Peru", "Puerto Rico", "United States",
                    "Austria", "Germany", "Netherlands", "Norway", "Spain"),
           order.by = "freq", keep.order = TRUE,
      nsets = length(asv_lst),
      mainbar.y.label = paste0(taxrank, " Intersections"),
      sets.x.label = paste0(taxrank, " number by country"),
      nintersects = 40)  
  pdf(file = paste0(temp_out,"rarefied_sharing_", taxrank, ".pdf"), 
      width = 9, height = 7, useDingbats = F)
  print(g)
  dev.off() 
}

```

## taxa plots
### phylums by country pie
```{r}
ft <- otu_table(phylo_global_p@otu_table) %>% as.data.frame() %>% t()
ft <- ft[meta_global$SampleID,]

ft_ra <- ft/rowSums(ft)
ft_ra_country <- aggregate(ft_ra, by = list(meta_global$Country), mean) %>%
  rename(Country = Group.1)

res <-  purrr::map_dfr(
    ft_ra_country %>% dplyr::select(-Country) %>% split(ft_ra_country$Country),
    function(dat){
      dat2 <- t(dat) %>% as.data.frame()
      names(dat2) <- "RA"
      dat3 <- dat2 %>% arrange(desc(RA)) %>% filter(RA > 0.01) %>% 
        rownames_to_column(var = "id")
      rbind(dat3, data.frame(id = "Other", RA = 1-sum(dat3$RA)))
      }, .id = "Country")

res <- res %>% left_join(taxa %>% dplyr::select(id, Phylum), by = "id") %>% 
  mutate(Taxa = ifelse(is.na(Phylum),"Other",Phylum))

temp <- res %>% dplyr::select(Taxa, RA) %>% group_by(Taxa) %>% dplyr::summarise(RA = mean(RA)) %>% arrange(desc(RA)) %>% filter(Taxa != "Other")

phylum_color = c(col_vector[1:(nrow(temp))],"Gray50")
names(phylum_color) = c(temp$Taxa, "Other")

#g <- ggplot(res, aes(x = "", y = RA, fill = Taxa)) + 
#  geom_bar(stat = "identity", width = 1, color = "white") + 
#  scale_fill_manual(values = phylum_color, name = "") + 
#  coord_polar("y", start=0) + 
#  facet_wrap(~Country) + 
#  theme_void() + theme(strip.text = element_text(face = "bold", size = 12)) 
#ggsave(filename = paste0(temp_out,"top_phylum_pie.pdf"), device = cairo_pdf,
#       plot = g, width = 14, height = 10, units = "in", dpi = 300)

g_lst <- lapply(res$Country %>% unique(), function(x){
  g <- ggplot(res %>% filter(Country == x),
              aes(x = "", y = RA, fill = Taxa)) + 
    geom_bar(stat = "identity", width = 1, color = "white") + 
    scale_fill_manual(values = phylum_color, name = "") + 
    labs(title = x) + 
    coord_polar("y", start=0) + 
    theme_void() + theme(plot.title = element_text(face = "bold", size = 12, hjust = 0.5))  
})
names(g_lst) <- res$Country %>% unique()

#layout <- "
#ABCDE#
#FGHIJK
#LMNOPQ
#"
#g <- g_lst$`Guinea Ecuatorial` + g_lst$Kenya + g_lst$Senegal + g_lst$`South Sudan` + g_lst$Tanzania +
#  g_lst$Ecuador + g_lst$ElSalvador + g_lst$Mexico + g_lst$Peru + g_lst$`Puerto Rico` + g_lst$`United States` + 
#  g_lst$Austria + g_lst$Germany + g_lst$Netherlands + g_lst$Norway + g_lst$Spain + guide_area() + 
#  plot_layout(design = layout, guides = "collect")

g <- g_lst$`Equatorial Guinea` + g_lst$Kenya + g_lst$Senegal + g_lst$`South Sudan` + g_lst$Tanzania +
  g_lst$Ecuador + g_lst$ElSalvador + g_lst$Mexico + g_lst$Peru + g_lst$`Puerto Rico` + g_lst$`United States` + 
  g_lst$Austria + g_lst$Germany + g_lst$Netherlands + g_lst$Norway + g_lst$Spain + 
  plot_layout(ncol = 4, guides = "collect")
ggsave(filename = paste0(temp_out,"top_phylum_pie.pdf"), device = cairo_pdf,
       plot = g, width = 14, height = 10, units = "in", dpi = 300)
```

### taxa by country bar
```{r}

for (taxrank in c("Species","Genus", "Family", "Phylum")){
  if(taxrank == "Species"){
    ft <- otu_table(phylo_global_s@otu_table) %>% as.data.frame() %>% t()
    top = 10
    taxa_temp <- taxa %>% mutate(taxa_long = str_c(Genus,Species, sep = ";"))
  }else if(taxrank == "Genus"){
    ft <- otu_table(phylo_global_g@otu_table) %>% as.data.frame() %>% t()
    top = 10
    taxa_temp <- taxa %>% mutate(taxa_long = str_c(Family,Genus, sep = ";"))
  }else if(taxrank == "Family"){
    ft <- otu_table(phylo_global_f@otu_table) %>% as.data.frame() %>% t()
    top = 10
    taxa_temp <- taxa %>% mutate(taxa_long = str_c(Order,Family, sep = ";"))
  }else{
    ft <- otu_table(phylo_global_p@otu_table) %>% as.data.frame() %>% t()
    top = 5
    taxa_temp <- taxa %>% mutate(taxa_long = Phylum)
  }

ft <- ft[meta_global$SampleID,]
ft_ra <- ft/rowSums(ft)
ft_ra_country <- aggregate(ft_ra, by = list(meta_global$Country), mean) %>%
  rename(Country = Group.1)

res <-  purrr::map_dfr(
    ft_ra_country %>% dplyr::select(-Country) %>% split(ft_ra_country$Country),
    function(dat){
      dat2 <- t(dat) %>% as.data.frame()
      names(dat2) <- "RA"
      dat3 <- dat2 %>% arrange(desc(RA)) %>% top_n(10, RA) %>% 
        filter(RA > 0.01) %>%
        rownames_to_column(var = "id")
      rbind(dat3, data.frame(id = "Other", RA = 1-sum(dat3$RA)))
      }, .id = "Country")

res <- res %>% left_join(taxa_temp, by = "id") %>% 
  mutate(Taxa = ifelse(is.na(taxa_long),"Other",taxa_long))

temp <- res %>% dplyr::select(Taxa, RA) %>% group_by(Taxa) %>% dplyr::summarise(RA = mean(RA)) %>% arrange(desc(RA)) %>% filter(Taxa != "Other")

taxa_color <- c(col_vector[1:(nrow(temp))],"Gray50")
names(taxa_color) <- c(temp$Taxa, "Other")

g <- ggplot(res %>% mutate(Taxa =  factor(Taxa, levels = names(taxa_color), ordered = T),
                          Country = factor(Country, levels = names(Country_color), ordered = T)), 
           aes(Country, RA, fill = Taxa)) + 
  geom_bar(stat="identity") + 
  labs(x = "", y = "Mean Relative Abundance") + 
  scale_fill_manual(values = taxa_color, name="") + 
  scale_y_continuous(expand=c(0,0)) + 
  scale_x_discrete(labels=Country_labels) + 
  guides(fill = guide_legend(ncol = 1)) +
  theme_bw() + theme(aspect.ratio = 1.5,
                     panel.background = element_rect(fill = NA),
                     panel.border = element_blank(),
                     panel.grid = element_blank(),
                     axis.line = element_blank(),
                     axis.ticks = element_blank(),
                     axis.text = element_text(size=12,color="black",face='bold'),
                     axis.text.x = element_markdown(size=12,color="black",face='bold',
                                                angle=90, hjust = 1, vjust = 0.5),
                     axis.title = element_text(size=12,color="black",face='bold'),
                     legend.text = element_text(size=10,color="black",face='bold'))
ggsave(filename = paste0(temp_out,"top_", taxrank, "_bar.pdf"), device = cairo_pdf,
       plot = g, width = 14, height = 12, units = "in", dpi = 300)

Country_ord = res %>% filter(id == res$id[1]) %>% arrange(desc(RA)) %>% pull(Country)
g <- ggplot(res %>% mutate(Taxa =  factor(Taxa, levels = names(taxa_color), ordered = T),
                          Country = factor(Country, levels = Country_ord, ordered = T)), 
           aes(Country, RA, fill = Taxa)) + 
  geom_bar(stat="identity") + 
  labs(x = "", y = "Mean Relative Abundance") + 
  scale_fill_manual(values = taxa_color, name="") + 
  scale_y_continuous(expand=c(0,0)) + 
  scale_x_discrete(labels=Country_labels) + 
  guides(fill = guide_legend(ncol = 1)) +
  theme_bw() + theme(aspect.ratio = 1.5,
                     panel.background = element_rect(fill = NA),
                     panel.border = element_blank(),
                     panel.grid = element_blank(),
                     axis.line = element_blank(),
                     axis.ticks = element_blank(),
                     axis.text = element_text(size=12,color="black",face='bold'),
                     axis.text.x = element_markdown(size=12,color="black",face='bold',
                                                angle=90, hjust = 1, vjust = 0.5),
                     axis.title = element_text(size=12,color="black",face='bold'),
                     legend.text = element_text(size=10,color="black",face='bold'))
ggsave(filename = paste0(temp_out,"top_", taxrank, "_bar_sorted.pdf"), device = cairo_pdf,
       plot = g, width = 14, height = 12, units = "in", dpi = 300)
}
```

## taxa prevalence
```{r}
for (taxrank in c("ASV", "Species","Genus", "Family", "Phylum")){
  if(taxrank == "ASV"){
    ft <- otu_table(phylo_global@otu_table) %>% as.data.frame()
    taxa_temp <- taxa %>% mutate(taxa_long = str_c(Genus,Species,ASV, sep = ";"))
  }else if(taxrank == "Species"){
    ft <- otu_table(phylo_global_s@otu_table) %>% as.data.frame()
    taxa_temp <- taxa %>% mutate(taxa_long = str_c(Genus,Species, sep = ";"))
  }else if(taxrank == "Genus"){
    ft <- otu_table(phylo_global_g@otu_table) %>% as.data.frame()
    taxa_temp <- taxa %>% mutate(taxa_long = str_c(Family,Genus, sep = ";"))
  }else if(taxrank == "Family"){
    ft <- otu_table(phylo_global_f@otu_table) %>% as.data.frame()
    taxa_temp <- taxa %>% mutate(taxa_long = str_c(Order,Family, sep = ";"))
  }else{
    ft <- otu_table(phylo_global_p@otu_table) %>% as.data.frame()
    taxa_temp <- taxa %>% mutate(taxa_long = Phylum)
  }
  n = length(phylo_global@sam_data@row.names)
  ft2 <- t(ft)
  ft <- ft[rowSums(ft)>0, ]
  ft <- ft/colSums(ft)[1]
  dat <- data.frame(id = rownames(ft), prevalence = rowSums(ft>0)/n*100, abundance =  rowMeans(ft))
  dat <- dat %>% left_join(taxa, by = "id")
  ft2 <- ft2[meta_global$SampleID,]
  asv_sum_country <- aggregate(ft2, by = list(meta_global$Country), sum)
  asv_sum_country_lst <- split(asv_sum_country[,-1], asv_sum_country[,1])
  asv_lst <- lapply(asv_sum_country_lst, function(dat){
    names(dat)[(which(dat[1,] > 1))]
  })
  universal_id <- Reduce(intersect, asv_lst)
  dat <- dat %>% mutate(Universal = ifelse(id %in% universal_id, "Y", "N"))
  write.csv(dat, file = paste0(temp_out,"Prevalence_", taxrank, "_in_global.csv"), row.names = F, quote = F)
  ft2_lst <- split(as.data.frame(ft2), meta_global$Country)
  res <- lapply(seq_along(ft2_lst), function(n){
    a <- ft2_lst[[n]]
    Country <- names(ft2_lst)[n]
    temp_pre <- colSums(a) /ncol(a) * 100 
    temp_dat <- data.frame(id = names(temp_pre), prevalence = temp_pre, abundance = colMeans(a)/(rowSums(a)[1]))
    temp_dat %>% top_n(n = 10, wt = prevalence) %>% mutate(Country = Country)
  })
  res_all <- do.call(rbind, res)
  write.csv(res_all, file = paste0(temp_out,"Prevalence_", taxrank, "_in_global_by_Country.csv"), row.names = F, quote = F)
}

```

## heatmap from high prevalence abundance taxa
```{r}
mat_col_fun = circlize::colorRamp2(c(-4, -3.3, -2.6, -1.9, -1.2, -0.5), c("#253494","#2c7fb8","#41b6c4", "#7fcdbb", "#c7e9b4", "#ffffcc"))
col_fun = circlize::colorRamp2(c(-2, 0, 2), c("green", "white", "red"))

prev = 30
ra = 0.01

for (taxrank in c("ASV", "Species","Genus", "Family")){
  if(taxrank == "ASV"){
    ft <- otu_table(phylo_global@otu_table) %>% as.data.frame()
    taxa_temp <- taxa %>% mutate(taxa_long = str_c(Family,Genus,Species,ASV, sep = ";"))
  }else if(taxrank == "Species"){
    ft <- otu_table(phylo_global_s@otu_table) %>% as.data.frame()
    taxa_temp <- taxa %>% mutate(taxa_long = str_c(Family,Genus,Species, sep = ";"))
  }else if(taxrank == "Genus"){
    ft <- otu_table(phylo_global_g@otu_table) %>% as.data.frame()
    taxa_temp <- taxa %>% mutate(taxa_long = str_c(Family,Genus, sep = ";"))
  }else if(taxrank == "Family"){
    ft <- otu_table(phylo_global_f@otu_table) %>% as.data.frame()
    taxa_temp <- taxa %>% mutate(taxa_long = str_c(Order,Family, sep = ";"))
  }
  select_top_pre <- read.csv(paste0(temp_out,"Prevalence_", taxrank, "_in_global_by_Country.csv"))
  top_pre_id <- select_top_pre$id %>% unique()
  dat <- read_csv(paste0(temp_out,"Prevalence_", taxrank, "_in_global.csv"))
  select_id <- dat %>% filter(prevalence>prev | abundance > ra) %>% pull(id)
  ft <- ft[rowSums(ft)>0, ]
  meta_global <- meta_global %>% arrange(Continent, Country)
  wft <- ft[select_id, meta_global %>% pull(SampleID)]
  if (nrow(wft)>50){
    wft <- wft[(rowSums(wft) %>% sort(.,decreasing = T))[1:50] %>% names(),]
  }
  wft <- log10((wft + 0.5)/colSums(ft)[1])
  wft <- wft %>% rownames_to_column(var="id") %>% 
    left_join(taxa_temp %>% dplyr::select(id, taxa_long), by = "id") %>% 
    dplyr::select(-id) %>% dplyr::select(taxa_long, everything())
  wft2 = wft %>% column_to_rownames(var = "taxa_long")
  df_row_name_label = structure(rownames(wft2), names = rownames(wft2))
  df_col = meta_global %>% dplyr::select(Continent, Country)
  column_ha = HeatmapAnnotation(df = df_col %>% dplyr::select(Continent, Country), 
                                col = list(Continent = Continent_color,
                                           Country = Country_color),
                                simple_anno_size = unit(8, "mm"), 
                                annotation_label = c("Continent", "Country"),
                                annotation_name_gp = gpar(fontsize = 14,fontface = "bold"), 
                                annotation_name_side = "left",
                                show_legend = F)
  row_dend = as.dendrogram(hclust(dist(wft2)))
  p1 = Heatmap(as.matrix(wft2), 
              col = mat_col_fun, 
              #name = "Relative Abundance",
              show_heatmap_legend = F,
              cluster_columns = F, show_column_names = F,
              #column_split = df_col$SamplingAge_group,
              cluster_rows = row_dend,
              row_names_gp = gpar(fontsize = 14),
              row_labels = df_row_name_label,
              row_dend_width = unit(15, "mm"),
              row_names_max_width = max_text_width(df_row_name_label, gp = gpar(fontsize = 14)),
              top_annotation = column_ha,
              height = unit(8, "mm")*dim(wft)[1],
              width = unit(0.4, "mm")*dim(wft)[2]
              )
  lgd1 = Legend(labels = names(Continent_color), title = "Continent", 
                legend_gp = gpar(fill = Continent_color),
                title_position = "topleft", 
                labels_gp = gpar(fontsize = 14, fontface = "bold"),
                title_gp = gpar(fontsize = 14, fontface = "bold"))
  lgd2 = Legend(labels = names(Country_color), title = "Country", 
                legend_gp = gpar(fill = Country_color),
                title_position = "topleft", 
                labels_gp = gpar(fontsize = 14, fontface = "bold"),
                title_gp = gpar(fontsize = 14, fontface = "bold"))
  lgd3 = Legend(col_fun = mat_col_fun, title = "Relative abundance", 
                at = c(-4, -3.3, -2.6, -1.9, -1.2, -0.5),                 
                labels = c("0.01%", "0.05%", "0.25%", "1.25%", "6.25%", "31.25%"), 
                title_position = "topleft",
                labels_gp = gpar(fontsize = 14, fontface = "bold"), 
                title_gp = gpar(fontsize = 14, fontface = "bold"))
  pd = packLegend(list = list(lgd1, lgd2, lgd3), direction = "vertical")  
  p = draw(p1, annotation_legend_side = "left", annotation_legend_list = pd)
  pdf(file = paste0(temp_out,"heatmap_pre_", prev, "_abund_", ra, "_country_", taxrank, "_supervised.pdf"), 
      width = ComplexHeatmap:::width(p) %>% as.numeric()/25.4, 
      height = ComplexHeatmap:::height(p) %>% as.numeric()/25.4, useDingbats = F)
  draw(p)
  dev.off()  
  
  p2 = Heatmap(as.matrix(wft2), 
              col = mat_col_fun, 
              show_heatmap_legend = F,
              cluster_columns = T, show_column_names = F,
              cluster_rows = row_dend,
              row_names_gp = gpar(fontsize = 14),
              row_labels = df_row_name_label,
              row_dend_width = unit(15, "mm"),
              row_names_max_width = max_text_width(df_row_name_label, gp = gpar(fontsize = 14)),
              top_annotation = column_ha,
              height = unit(8, "mm")*dim(wft)[1],
              width = unit(0.4, "mm")*dim(wft)[2]
              )  
  p = draw(p2, annotation_legend_side = "left", annotation_legend_list = pd)
  pdf(file = paste0(temp_out,"heatmap_pre_", prev, "_abund_", ra, "_country_", taxrank, "_unsupervised.pdf"), 
      width = ComplexHeatmap:::width(p) %>% as.numeric()/25.4, 
      height = ComplexHeatmap:::height(p) %>% as.numeric()/25.4, useDingbats = F)
  draw(p)
  dev.off()
  
  wft <- ft[top_pre_id, meta_global %>% pull(SampleID)]
  if (nrow(wft)>50){
    wft <- wft[(rowSums(wft) %>% sort(.,decreasing = T))[1:50] %>% names(),]
  }
  wft <- log10((wft + 0.5)/colSums(ft)[1])
  wft <- wft %>% rownames_to_column(var="id") %>% 
    left_join(taxa_temp %>% dplyr::select(id, taxa_long), by = "id") %>% 
    dplyr::select(-id) %>% dplyr::select(taxa_long, everything())
  wft2 = wft %>% column_to_rownames(var = "taxa_long")
  df_row_name_label = structure(rownames(wft2), names = rownames(wft2))
  row_dend = as.dendrogram(hclust(dist(wft2)))
  
  p3 = Heatmap(as.matrix(wft2), 
              col = mat_col_fun, 
              #name = "Relative Abundance",
              show_heatmap_legend = F,
              cluster_columns = F, show_column_names = F,
              #column_split = df_col$SamplingAge_group,
              cluster_rows = row_dend,
              row_names_gp = gpar(fontsize = 14),
              row_labels = df_row_name_label,
              row_dend_width = unit(15, "mm"),
              row_names_max_width = max_text_width(df_row_name_label, gp = gpar(fontsize = 14)),
              top_annotation = column_ha,
              height = unit(8, "mm")*dim(wft)[1],
              width = unit(0.4, "mm")*dim(wft)[2]
              )  
  p = draw(p3, annotation_legend_side = "left", annotation_legend_list = pd)
  pdf(file = paste0(temp_out,"heatmap_top_pre_by_country_", taxrank, "_supervised.pdf"), 
      width = ComplexHeatmap:::width(p) %>% as.numeric()/25.4, 
      height = ComplexHeatmap:::height(p) %>% as.numeric()/25.4, useDingbats = F)
  draw(p)
  dev.off()    
  
  p4 = Heatmap(as.matrix(wft2), 
              col = mat_col_fun, 
              show_heatmap_legend = F,
              cluster_columns = T, show_column_names = F,
              cluster_rows = row_dend,
              row_names_gp = gpar(fontsize = 14),
              row_labels = df_row_name_label,
              row_dend_width = unit(15, "mm"),
              row_names_max_width = max_text_width(df_row_name_label, gp = gpar(fontsize = 14)),
              top_annotation = column_ha,
              height = unit(8, "mm")*dim(wft)[1],
              width = unit(0.4, "mm")*dim(wft)[2]
              )  
  p = draw(p4, annotation_legend_side = "left", annotation_legend_list = pd)
  pdf(file = paste0(temp_out,"heatmap_top_pre_by_country_", taxrank, "_unsupervised.pdf"), 
      width = ComplexHeatmap:::width(p) %>% as.numeric()/25.4, 
      height = ComplexHeatmap:::height(p) %>% as.numeric()/25.4, useDingbats = F)
  draw(p)
  dev.off()  
}

```

## bifido
```{r}
ft <- otu_table(phylo_global_g@otu_table) %>% as.data.frame() %>% 
  rownames_to_column(var = "id") %>% 
  left_join(taxa, by = "id") %>% 
  filter(Genus == "g_Bifidobacterium") %>% 
  column_to_rownames(var = "id") %>% t() %>% as.data.frame() %>% 
  rownames_to_column(var = "SampleID") 

names(ft) <- c("SampleID","Count")
ft$Count <- as.integer(ft$Count)
ft$RA <- ft$Count/2857

dat <- ft %>% left_join(meta_global, by = "SampleID") %>% 
  mutate(Country = factor(Country,
                          levels = c("Equatorial Guinea", "Kenya", "Senegal", "South Sudan", "Tanzania",
                                     "Ecuador", "ElSalvador", "Mexico", "Peru", "Puerto Rico", "United States",
                                     "Austria", "Germany", "Netherlands", "Norway", "Spain"),
                          ordered = T)) %>% 
  filter(!is.na(Country))

res <- comp_kw_aov(wdat = dat, x = "Country", y = "RA")
res_summary <- dat %>% dplyr::select(RA, Country) %>% 
  group_by(Country) %>% 
  summarise_all(my_summarize) %>% 
  ungroup() %>%
  unnest(cols = RA) %>% 
  left_join(res$grp, by = c("Country"="Var")) %>% 
  mutate(N_lab = str_c("",N))


g <- ggplot(dat, aes(Country, RA)) + 
  geom_boxplot(aes(color = Country, fill = Country),alpha = 0.7,  outlier.alpha = 0) + 
  geom_point(aes(color = Country), position = position_jitterdodge()) + 
  geom_text(data = res_summary, 
            aes(x =  Country, y = 1.08 * Max, label = KW_group)) +
  geom_text(data = res_summary, 
            aes(x =  Country, y = -0.01, label = N_lab)) +
  scale_color_manual(values = Country_color, aesthetics = c("color","fill")) + 
  scale_x_discrete(labels=Country_labels) + 
  labs(x = "", y = "Bifidobacterium Relative abundance") +
  theme_bw() + theme(#aspect.ratio = 0.8,
    legend.position="left",
    panel.background = element_rect(fill = NA),
    strip.text = element_text(size=12,color="black",face='bold'),
    axis.title = element_text(size=12,color="black",face='bold'),
    axis.text = element_text(size=12,color="black",face='bold'),
    axis.text.x = element_markdown(size=12, face='bold',angle=90,vjust = 0.5, hjust = 1),
    axis.text.y = element_text(size=12,color="black",face='bold'),
    legend.text = element_text(size=12,color="black",face='bold'),
    legend.title = element_text(size=12,color="black",face='bold'),
    title = element_text(size=12,color="black",face='bold'))

ggsave(filename = paste0(temp_out, "bifido_by_Country_global.pdf"), device = cairo_pdf, 
         plot = g, width = 7, height = 7, units = "in", dpi = 300) 

## order bifido
g <- ggplot(dat %>% mutate(Country = factor(Country, levels= res_summary %>% arrange(desc(Med)) %>% pull(Country), ordered = T)), 
            aes(Country, RA)) + 
  geom_boxplot(aes(color = Country, fill = Country),alpha = 0.7,  outlier.alpha = 0) + 
  geom_point(aes(color = Country), position = position_jitterdodge()) + 
  geom_text(data = res_summary, 
            aes(x =  Country, y = 1.08 * Max, label = KW_group)) +
  geom_text(data = res_summary, 
            aes(x =  Country, y = -0.01, label = N_lab)) +
  scale_color_manual(values = Country_color, aesthetics = c("color","fill")) + 
  scale_x_discrete(labels=Country_labels) + 
  labs(x = "", y = "Bifidobacterium Relative abundance") +
  theme_bw() + theme(#aspect.ratio = 0.8,
    legend.position="left",
    panel.background = element_rect(fill = NA),
    strip.text = element_text(size=12,color="black",face='bold'),
    axis.title = element_text(size=12,color="black",face='bold'),
    axis.text = element_text(size=12,color="black",face='bold'),
    axis.text.x = element_markdown(size=12, face='bold',angle=90,vjust = 0.5, hjust = 1),
    axis.text.y = element_text(size=12,color="black",face='bold'),
    legend.text = element_text(size=12,color="black",face='bold'),
    legend.title = element_text(size=12,color="black",face='bold'),
    title = element_text(size=12,color="black",face='bold'))

ggsave(filename = paste0(temp_out, "bifido_by_Country_global_ordered.pdf"), device = cairo_pdf, 
       plot = g, width = 7, height = 7, units = "in", dpi = 300) 


res <- comp_kw_aov(wdat = dat, x = "Continent", y = "RA")
res_summary <- dat %>% dplyr::select(RA, Continent) %>% 
  group_by(Continent) %>% 
  summarise_all(my_summarize) %>% 
  ungroup() %>%
  unnest(cols = RA) %>% 
  left_join(res$grp, by = c("Continent"="Var"))

g <- ggplot(dat, aes(Continent, RA)) + 
  geom_boxplot(aes(color = Continent, fill = Continent),alpha = 0.7,  outlier.alpha = 0) + 
  geom_point(aes(color = Continent), position = position_jitterdodge()) + 
  geom_text(data = res_summary, 
            aes(x =  Continent, y = 1.08 * Max, label = KW_group)) +
  scale_color_manual(values = Continent_color, aesthetics = c("color","fill")) + 
  #scale_x_discrete(labels=Country_labels) + 
  labs(x = "", y = "Bifidobacterium Relative abundance") +
  theme_bw() + theme(#aspect.ratio = 0.8,
    legend.position="none",
    panel.background = element_rect(fill = NA),
    strip.text = element_text(size=12,color="black",face='bold'),
    axis.title = element_text(size=12,color="black",face='bold'),
    axis.text = element_text(size=12,color="black",face='bold'),
    axis.text.x = element_markdown(size=12, face='bold',angle=90,vjust = 0.5, hjust = 1),
    axis.text.y = element_text(size=12,color="black",face='bold'),
    legend.text = element_text(size=12,color="black",face='bold'),
    legend.title = element_text(size=12,color="black",face='bold'),
    title = element_text(size=12,color="black",face='bold'))

ggsave(filename = paste0(temp_out, "bifidobacterium_by_Continent_global.pdf"), device = cairo_pdf, 
         plot = g, width = 14, height = 10, units = "in", dpi = 300) 


```







