---
title: "Alpha diversity"
author: "Haipeng Sun"
date: "8/1/2022"
output: html_document
---

## library
```{r setup, message=FALSE, warning=FALSE}
library(phyloseq)
library(purrr)
library(furrr)
library(picante)
library(vegan)
library(ggpubr)
library(effectsize)
library(ggtext)
library(glue)
library(RColorBrewer)
library(tidyverse)
```

## prepare (run first time only)
### load data
```{r}
path_rec <- "~/Dropbox/Rutgers/20220606_RUN41_milk/Data/"
temp_out <- "~/Dropbox/Rutgers/20220606_RUN41_milk/Data/output/global/"

a <- read.table(paste0(path_rec, "milk_mycobiome_handoff/dada2/dada2_feature_with-taxon-table.tsv"), sep = "\t")
aa <- a$V84 %>% str_split_fixed(";", 8) %>% 
  as.data.frame() %>% 
  mutate(
    Kingdom = str_replace(V1,"k__","k_"),
    Phylum = str_remove(V2," p__"), Phylum = str_c("p_", Phylum, sep = ""),
    Class = str_remove(V3," c__"), Class = str_c("c_", Class, sep = ""),
    Order = str_remove(V4," o__"), Order = str_c("o_", Order, sep = ""),
    Family = str_remove(V5," f__"),Family = str_c("f_", Family, sep = ""),
    Genus = str_remove(V6," g__"), Genus = str_c("g_", Genus, sep = ""),
    Species = str_remove(V7," s__"), Species = str_c("s_", Species, sep = ""),
    SH = str_remove(V8," sh__"), SH = str_c("sh_", SH, sep = "")
  ) %>% 
  select(Kingdom:SH)
taxa_ITS <- bind_cols(id = a$V1, aa) %>% 
  mutate(ASV = str_c("asv_", 1:nrow(aa)),
         taxa_long = str_c(Kingdom,Phylum,Class,Order,Family,Genus,Species,ASV,sep = ";"))

ft_ITS <- read.table(paste0(path_rec, "milk_mycobiome_handoff/dada2/dada2_feature_table.tsv"), 
                     sep = "\t", comment.char = "", skip = 1, header = T) %>% 
  column_to_rownames(var = "X.OTU.ID") 
colnames(ft_ITS) <- colnames(ft_ITS) %>% str_remove("^X") %>% str_remove("\\.filt")
ft_ITS <- ft_ITS[,colSums(ft_ITS)>0]
```

### load 16S and merge
```{r}
load("~/Library/CloudStorage/Dropbox/rutgers/20220606_RUN41_milk/Data/Global.Rdata")
load(file = "~/Library/CloudStorage/Dropbox/Rutgers/20220606_RUN41_milk/Data/phylo_meta.Rdata")

meta_global <- meta_global %>% mutate(SampleID_clean = str_remove_all(SampleID, " ")) %>% filter(Project != "Covid Mom")
meta_all <- meta_all %>% mutate(SampleID_clean = str_remove_all(SampleID, " ")) %>% filter(Project != "Covid Mom")

a <- meta_all %>% filter(SampleID_clean %in% names(ft_ITS)) %>% filter(Project != "Covid Mom")
write.csv(a, file = "~/Dropbox/Rutgers/20220606_RUN41_milk/Data/fungi_sample_common.csv")

both_sample <- intersect(meta_global$SampleID_clean, names(ft_ITS))
meta_both <- meta_global %>% filter(SampleID_clean %in% both_sample)
meta_both %>% count(Continent, Country)

ft_ITS %>% select(meta_both$SampleID_clean) %>% 
  colSums() %>% sort()
```

### save
```{r}
 # save(ft_ITS, taxa_ITS, meta_both,
 #      file = "~/Library/CloudStorage/Dropbox/rutgers/20220606_RUN41_milk/Data/Global_ITS.Rdata")
```

## load global data
```{r}
load("~/Library/CloudStorage/Dropbox/rutgers/20220606_RUN41_milk/Data/Global_ITS.Rdata")
load("~/Library/CloudStorage/Dropbox/rutgers/20220606_RUN41_milk/Data/Global.Rdata")
temp_out = "~/Library/CloudStorage/Dropbox/rutgers/20220606_RUN41_milk/Data/output/global/"
```

### summary
```{r}
meta_global_rf <- meta_global_rf %>% filter(decontam_cleaned>depth) %>%  filter(Project != "Covid Mom")
meta_both <- meta_both %>% filter(Project != "Covid Mom", SampleID != "BR34.1")
meta_global <- meta_global %>% filter(Project != "Covid Mom")
meta_both %>% count(Country)
meta_global %>% count(Continent, Country)

write_csv(meta_global, file = paste0(temp_out,"meta_global.csv"))
write_csv(meta_both, file = paste0(temp_out,"meta_both.csv"))
```

## Taxa
### function
```{r}
aggregate_ft <- function(ft, taxa, L = "Genus"){
  #input: 
  #ft : feature in column matrix
  #taxa : df with id, taxa levels
  #L : taxa levels to aggregate c("Phylum","Class","Order", "Family", "Genus","Species")
  #output: feature in column matrix to a taxa level
  ft_agg <- ft %>% t() %>% as.data.frame() %>% 
    rownames_to_column(var = "id") %>% 
    left_join(taxa %>% select(id, Kingdom:Species), by = "id")
  if(L == "Species"){
    ft_agg <- ft_agg %>% mutate(grp = str_c(Kingdom, Phylum, Class, Order, Family, Genus, Species, sep = ";"))
  }else if(L == "Genus"){
    ft_agg <- ft_agg %>% mutate(grp = str_c(Kingdom, Phylum, Class, Order, Family, Genus, sep = ";"))
  }else if(L == "Family"){
    ft_agg <- ft_agg %>% mutate(grp = str_c(Kingdom, Phylum, Class, Order, Family, sep = ";"))
  }else if(L == "Order"){
    ft_agg <- ft_agg %>% mutate(grp = str_c(Kingdom, Phylum, Class, Order, sep = ";"))
  }else if(L == "Class"){
    ft_agg <- ft_agg %>% mutate(grp = str_c(Kingdom, Phylum, Class, sep = ";"))
  }else if(L == "Phylum"){
    ft_agg <- ft_agg %>% mutate(grp = str_c(Kingdom,Phylum, sep = ";"))
  }
  ft_agg <- ft_agg %>% select(-c(id,Kingdom:Species)) %>% 
    select(grp ,dplyr::everything()) %>% 
    group_by(grp) %>%
    summarise(across(everything(), sum),
              .groups = 'drop') %>% 
    ungroup() %>% 
    column_to_rownames(var = "grp") %>% t()
  ft_agg
}

```

### bar plot
```{r}
ft_its_wk <- ft_ITS %>% t() %>% 
  as.data.frame() %>% rownames_to_column(var = "SampleID_clean") %>% 
  left_join(meta_both %>% select(SampleID, SampleID_clean, Country), by = "SampleID_clean") %>% 
  filter(!is.na(Country)) %>% 
  select(-c(SampleID, Country)) %>% 
  column_to_rownames(var = "SampleID_clean")
  
ft_its_wk <- ft_its_wk[,colSums(ft_its_wk)>0]
ft_its_wk <- ft_its_wk[rowSums(ft_its_wk)>0,]

ft_ITS_clean <- ft_ITS %>% as.data.frame() %>% 
  rownames_to_column(var = "id") %>% 
  left_join(taxa_ITS %>% select(id, Kingdom:Species), by = "id") %>% 
  filter(Kingdom == "k_Fungi", Phylum != "p_")

ft_ITS_clean_wk <- ft_ITS_clean %>% column_to_rownames(var = "id") %>% 
  select(-c(Kingdom:Species)) %>% 
  select(all_of(meta_both$SampleID_clean))

## Species
ft_ITS_clean_wk_s <- ft_ITS_clean_wk %>% rownames_to_column(var = "id") %>% 
  left_join(taxa_ITS %>% select(id, Kingdom:Species), by = "id") %>% 
  mutate(grp = str_c(Kingdom, Phylum, Class, Order, Family, Genus, Species, sep = ";")) %>% 
  mutate(taxa_label = case_when(Species == "s_" & Genus != "g_" ~ str_c(Phylum, Genus, Species, sep = ";"),
                                Species == "s_" & Genus == "g_" & Family != "f_" ~ str_c(Phylum, Family, Species, sep = ";"),
                                Species == "s_" & Genus == "g_" & Family == "f_" & Order != "o_" ~ str_c(Phylum, Order, Species, sep = ";"),
                                Species == "s_" & Genus == "g_" & Family == "f_" & Order == "o_" & Class != "c_" ~ str_c(Phylum, Class, Species, sep = ";"),
                                TRUE ~ str_c(Phylum, Species, sep = ";")))

taxa_label <- ft_ITS_clean_wk_s %>% select(grp, taxa_label) %>% unique()

ft_ITS_clean_wk_s <- ft_ITS_clean_wk_s %>% select(-c(id,Kingdom:Species,grp)) %>% 
  select(taxa_label ,dplyr::everything()) %>% 
  group_by(taxa_label) %>%
  summarise(across(everything(), sum),
            .groups = 'drop') %>% 
  ungroup() %>% 
  column_to_rownames(var = "taxa_label")

ft_ITS_clean_wk_s <- ft_ITS_clean_wk_s[, colSums(ft_ITS_clean_wk_s)>0]

top_id <- (rowMeans(ft_ITS_clean_wk_s) %>% sort(decreasing = TRUE) %>% names())[1:20]

ft_tmp <- ft_ITS_clean_wk_s %>% rownames_to_column(var = "taxa_label") %>% 
  mutate(taxa_label = ifelse(taxa_label %in% top_id, taxa_label, "other")) %>% 
  group_by(taxa_label) %>%
  summarise(across(everything(), sum),
            .groups = 'drop') %>% 
  ungroup() %>% 
  pivot_longer(cols = -taxa_label) 

sample_ord <- meta_both %>% arrange(Continent, Country, SampleID_clean) %>% pull(SampleID_clean)

col_vector = c(brewer.pal(12, "Set3"), brewer.pal(12, "Paired"), 
               brewer.pal(8, "Set2"), brewer.pal(7, "Accent")) %>% unique()
cols = c(col_vector[1:21])

g <- ggplot(ft_tmp %>% mutate(name = factor(name, levels = sample_ord, ordered = TRUE)),
            aes(name, value)) +
  geom_col(aes(fill = taxa_label), position = "stack") +
  scale_fill_manual(values = cols) + 
  guides(fill=guide_legend(ncol =1)) + 
  labs(x = "", y = "Read counts") + 
  theme_bw() + theme(#aspect.ratio = 0.8,
    legend.position="right",
    panel.background = element_rect(fill = NA),
    strip.text = element_text(size=12,color="black",face='bold'),
    axis.title = element_text(size=12,color="black",face='bold'),
    axis.text = element_text(size=12,color="black",face='bold'),
    axis.text.x = element_markdown(size=12, face='bold',angle=90,vjust = 0.5, hjust = 1),
    axis.text.y = element_text(size=12,color="black",face='bold'),
    legend.text = element_text(size=12,color="black",face='bold'),
    legend.title = element_text(size=12,color="black",face='bold'),
    title = element_text(size=12,color="black",face='bold'))

ggsave(filename = paste0(temp_out, "read_count_fungi_species_per_sample.pdf"), device = cairo_pdf, 
       plot = g, width = 14, height = 8, units = "in", dpi = 300)  

ft_ITS_clean_wk <- ft_ITS_clean_wk[, colSums(ft_ITS_clean_wk)>0]
ra_ITS_clean_wk <- sweep(ft_ITS_clean_wk, 2, colSums(ft_ITS_clean_wk), `/`)

ra_ITS_clean_wk_s <- ra_ITS_clean_wk %>% rownames_to_column(var = "id") %>% 
  left_join(taxa_ITS %>% select(id, Kingdom:Species), by = "id") %>% 
  mutate(grp = str_c(Kingdom, Phylum, Class, Order, Family, Genus, Species, sep = ";")) %>% 
  mutate(taxa_label = case_when(Species == "s_" & Genus != "g_" ~ str_c(Phylum, Genus, Species, sep = ";"),
                                Species == "s_" & Genus == "g_" & Family != "f_" ~ str_c(Phylum, Family, Species, sep = ";"),
                                Species == "s_" & Genus == "g_" & Family == "f_" & Order != "o_" ~ str_c(Phylum, Order, Species, sep = ";"),
                                Species == "s_" & Genus == "g_" & Family == "f_" & Order == "o_" & Class != "c_" ~ str_c(Phylum, Class, Species, sep = ";"),
                                TRUE ~ str_c(Phylum, Species, sep = ";")))

taxa_label <- ra_ITS_clean_wk_s %>% select(grp, taxa_label) %>% unique()

ra_ITS_clean_wk_s <- ra_ITS_clean_wk_s %>% select(-c(id,Kingdom:Species,grp)) %>% 
  select(taxa_label ,dplyr::everything()) %>% 
  group_by(taxa_label) %>%
  summarise(across(everything(), sum),
            .groups = 'drop') %>% 
  ungroup() %>% 
  column_to_rownames(var = "taxa_label")

top_id <- (rowMeans(ra_ITS_clean_wk_s) %>% sort(decreasing = TRUE) %>% names())[1:20]

ra_tmp <- ra_ITS_clean_wk_s %>% rownames_to_column(var = "taxa_label") %>% 
  mutate(taxa_label = ifelse(taxa_label %in% top_id, taxa_label, "other")) %>% 
  group_by(taxa_label) %>%
  summarise(across(everything(), sum),
            .groups = 'drop') %>% 
  ungroup() %>% 
  pivot_longer(cols = -taxa_label) 

sample_ord <- meta_both %>% arrange(Continent, Country, SampleID_clean) %>% pull(SampleID_clean)

col_vector = c(brewer.pal(12, "Set3"), brewer.pal(12, "Paired"), 
               brewer.pal(8, "Set2"), brewer.pal(7, "Accent")) %>% unique()
cols = c(col_vector[1:21])

g <- ggplot(ra_tmp %>% mutate(name = factor(name, levels = sample_ord, ordered = TRUE)),
            aes(name, value)) +
  geom_col(aes(fill = taxa_label), position = "stack") +
  scale_fill_manual(values = cols) + 
  guides(fill=guide_legend(ncol =1)) + 
  labs(x = "", y = "Read counts") + 
  theme_bw() + theme(#aspect.ratio = 0.8,
    legend.position="right",
    panel.background = element_rect(fill = NA),
    strip.text = element_text(size=12,color="black",face='bold'),
    axis.title = element_text(size=12,color="black",face='bold'),
    axis.text = element_text(size=12,color="black",face='bold'),
    axis.text.x = element_markdown(size=12, face='bold',angle=90,vjust = 0.5, hjust = 1),
    axis.text.y = element_text(size=12,color="black",face='bold'),
    legend.text = element_text(size=12,color="black",face='bold'),
    legend.title = element_text(size=12,color="black",face='bold'),
    title = element_text(size=12,color="black",face='bold'))

ggsave(filename = paste0(temp_out, "RA_fungi_species_per_sample.pdf"), device = cairo_pdf, 
       plot = g, width = 14, height = 8, units = "in", dpi = 300)  

```

### prevalence Species
```{r}
dat <- data.frame(pre = rowSums(ft_ITS_clean_wk_s>0), taxa = rownames(ft_ITS_clean_wk_s))

write_tsv(dat, paste0(temp_out, "prev_fungi.tsv"))

```


## alpha TBD
### function
```{r}
comp_kw_aov = function(wdat, x, y){
  #input data, respond variable y, categorize variable x
  require(agricolae)
  ktest1 = kruskal(wdat[y], wdat[x], alpha = 0.05, p.adj="none", group=T, main = "wdat", console=FALSE)
  out_g_1 = ktest1$groups %>% rownames_to_column(var = "Var") %>% dplyr::select(Var, groups) %>% rename(KW_group = groups)
  ktest2 = kruskal(wdat[y], wdat[x], alpha = 0.05, p.adj="none", group=F, main = "wdat", console=FALSE)
  out_c_1 = ktest2$comparison %>% rownames_to_column(var = "comp") %>% dplyr::select(comp, pvalue) %>% rename(KW_pvalue = pvalue)
  fit = aov(as.formula(paste0(y, "~", x)), wdat)
  tukey1 = HSD.test(fit, x, group = T)
  out_g_2 = tukey1$groups %>% rownames_to_column(var = "Var") %>% dplyr::select(Var, groups) %>% rename(aov_group = groups)
  tukey2 = HSD.test(fit, x, group = F)
  out_c_2 = tukey2$comparison %>% rownames_to_column(var = "comp") %>% dplyr::select(comp, pvalue) %>% rename(aov_pvalue = pvalue)
  out_g = merge(out_g_1, out_g_2,by = 1)
  out_c = merge(out_c_1, out_c_2,by = 1)
  res = list(out_g, out_c)
  names(res) = c("grp","comp")
  res
}
```


### alpha linear model global
```{r}
temp_out <- "~/Library/CloudStorage/Dropbox/rutgers/20220606_RUN41_milk/Data/output/global/alpha/"
metric <- names(alpha_global)[2:5]
names(metric) <- names(alpha_global)[2:5]
dat <- alpha_global %>% left_join(meta_global, by = "SampleID")

# country
alpha_lm_coef <- map_dfr(metric, function(a){
  fit <- lm(as.formula(paste0(a, "  ~ Country")), data = dat)
  anova_fit <- anova(fit)
  sum_fit <- summary(fit)
  effect_fit <- effectsize(anova_fit, "omega")
  res_coef <- sum_fit$coefficients %>% as.data.frame() %>% 
    rownames_to_column(var = "Var") %>% filter(Var != "(Intercept)")
  res_anova <- right_join(anova_fit %>% as.data.frame() %>% rownames_to_column(var = "Parameter"),
                          effect_fit %>% as.data.frame(), by = "Parameter")
  res_coef$Metrics = a
  res_coef
})
write.csv(alpha_lm_coef, row.names = FALSE,
          file = paste0(temp_out,"alpha_lm_coef_Country.csv"))

alpha_lm_omega <- map_dfr(metric, function(a){
  fit <- lm(as.formula(paste0(a, "  ~ Country")), data = dat)
  anova_fit <- anova(fit)
  sum_fit <- summary(fit)
  effect_fit <- effectsize(anova_fit, "omega")
  res_coef <- sum_fit$coefficients %>% as.data.frame() %>% 
    rownames_to_column(var = "Var") %>% filter(Var != "(Intercept)")
  res_anova <- right_join(anova_fit %>% as.data.frame() %>% rownames_to_column(var = "Parameter"),
                          effect_fit %>% as.data.frame(), by = "Parameter")
  res_anova$Metrics = a
  res_anova
})
write.csv(alpha_lm_omega, row.names = FALSE,
          file = paste0(temp_out,"alpha_lm_omega_Country.csv"))

# Continent
alpha_lm_coef <- map_dfr(metric, function(a){
  fit <- lm(as.formula(paste0(a, "  ~ Continent")), data = dat)
  anova_fit <- anova(fit)
  sum_fit <- summary(fit)
  effect_fit <- effectsize(anova_fit, "omega")
  res_coef <- sum_fit$coefficients %>% as.data.frame() %>% 
    rownames_to_column(var = "Var") %>% filter(Var != "(Intercept)")
  res_anova <- right_join(anova_fit %>% as.data.frame() %>% rownames_to_column(var = "Parameter"),
                          effect_fit %>% as.data.frame(), by = "Parameter")
  res_coef$Metrics = a
  res_coef
})
write.csv(alpha_lm_coef, row.names = FALSE,
          file = paste0(temp_out,"alpha_lm_coef_Continent.csv"))

alpha_lm_omega <- map_dfr(metric, function(a){
  fit <- lm(as.formula(paste0(a, "  ~ Continent")), data = dat)
  anova_fit <- anova(fit)
  sum_fit <- summary(fit)
  effect_fit <- effectsize(anova_fit, "omega")
  res_coef <- sum_fit$coefficients %>% as.data.frame() %>% 
    rownames_to_column(var = "Var") %>% filter(Var != "(Intercept)")
  res_anova <- right_join(anova_fit %>% as.data.frame() %>% rownames_to_column(var = "Parameter"),
                          effect_fit %>% as.data.frame(), by = "Parameter")
  res_anova$Metrics = a
  res_anova
})
write.csv(alpha_lm_omega, row.names = FALSE,
          file = paste0(temp_out,"alpha_lm_omega_Continent.csv"))

```


### alpha in Global project plot
```{r}
temp_out <- "~/Library/CloudStorage/Dropbox/rutgers/20220606_RUN41_milk/Data/output/global/alpha/"
metric <- names(alpha_global)[2:5]
names(metric) <- names(alpha_global)[2:5]
dat <- alpha_global %>% left_join(meta_global, by = "SampleID")


# Country
alpha_Country_grp <- map_dfr(metric, function(a){
  res <- comp_kw_aov(wdat = dat, x = "Country", y = a)
  res$grp$Metrics = a
  res$grp
})
write.csv(alpha_Country_grp, row.names = FALSE,
          file = paste0(temp_out,"alpha_by_Country_kw_aov_grp.csv"))
alpha_Country_pvalue <- map_dfr(metric, function(a){
  res <- comp_kw_aov(wdat = dat, x = "Country", y = a)
  res$comp$Metrics = a
  res$comp
})
write.csv(alpha_Country_pvalue, row.names = FALSE,
          file = paste0(temp_out,"alpha_by_Country_kw_pvalue.csv"))

alpha_Country_summary <- dat %>% dplyr::select(Faith_PD:Pielou_evenness, Country) %>% 
  group_by(Country) %>% 
  summarise_all(my_summarize) %>% 
  ungroup() %>%
  pivot_longer(-Country,
               names_to = "Metrics",
               values_to = "value") %>% 
  unnest(cols = value) %>% 
  left_join(alpha_Country_grp, by = c("Country"="Var", "Metrics"="Metrics"))

wdat <- dat %>% 
  mutate(Country = factor(Country,
                          levels = names(Country_color),
                          ordered = T)) %>% 
  dplyr::select(SampleID, Country, Faith_PD:Pielou_evenness) %>% 
  pivot_longer(Faith_PD:Pielou_evenness, names_to = "Metrics", values_to = "value")

g <- ggplot(wdat, aes(Country, value)) + 
  geom_boxplot(aes(color = Country, fill = Country),alpha = 0.7,  outlier.alpha = 0) + 
  geom_point(aes(color = Country), position = position_jitterdodge()) + 
  geom_text(data = alpha_Country_summary, 
            aes(x =  Country, y = 1.08 * Max, label = KW_group)) + 
  scale_color_manual(values = Country_color, aesthetics = c("color","fill")) + 
  scale_x_discrete(labels=Country_labels) + 
  labs(x = "", y = "") +
  facet_wrap(~Metrics, nrow = 2, scales = "free") +
  theme_bw() + theme(#aspect.ratio = 0.8,
                     legend.position="none",
                     panel.background = element_rect(fill = NA),
                     strip.text = element_text(size=12,color="black",face='bold'),
                     axis.title = element_text(size=12,color="black",face='bold'),
                     axis.text = element_text(size=12,color="black",face='bold'),
                     axis.text.x = element_markdown(size=12, face='bold',angle=90,vjust = 0.5, hjust = 1),
                     axis.text.y = element_text(size=12,color="black",face='bold'),
                     legend.text = element_text(size=12,color="black",face='bold'),
                     legend.title = element_text(size=12,color="black",face='bold'),
                     title = element_text(size=12,color="black",face='bold'))
ggsave(filename = paste0(temp_out, "alpha_by_Country_full.pdf"), device = cairo_pdf, 
         plot = g, width = 14, height = 10, units = "in", dpi = 300) 

# order by faith PD
Country_ord <- alpha_Country_summary %>% filter(Metrics == "Faith_PD") %>% 
  dplyr::select(Country, Med) %>% 
  left_join(meta_global %>% dplyr::select(Country, Continent) %>% unique(), by = "Country") %>% 
  arrange(Continent, desc(Med)) %>% pull(Country)
wdat$Country = factor(wdat$Country, levels = Country_ord, ordered = T)

g <- ggplot(wdat, aes(Country, value)) + 
  geom_boxplot(aes(color = Country, fill = Country),alpha = 0.7,  outlier.alpha = 0) + 
  geom_point(aes(color = Country), position = position_jitterdodge()) + 
  geom_text(data = alpha_Country_summary, 
            aes(x =  Country, y = 1.08 * Max, label = KW_group)) + 
  scale_color_manual(values = Country_color, aesthetics = c("color","fill")) + 
  scale_x_discrete(labels=Country_labels) + 
  labs(x = "", y = "") +
  facet_wrap(~Metrics, nrow = 2, scales = "free") +
  theme_bw() + theme(#aspect.ratio = 0.8,
                     legend.position="none",
                     panel.background = element_rect(fill = NA),
                     strip.text = element_text(size=12,color="black",face='bold'),
                     axis.title = element_text(size=12,color="black",face='bold'),
                     axis.text = element_text(size=12,color="black",face='bold'),
                     axis.text.x = element_markdown(size=12, face='bold',angle=90,vjust = 0.5, hjust = 1),
                     axis.text.y = element_text(size=12,color="black",face='bold'),
                     legend.text = element_text(size=12,color="black",face='bold'),
                     legend.title = element_text(size=12,color="black",face='bold'),
                     title = element_text(size=12,color="black",face='bold'))
ggsave(filename = paste0(temp_out, "alpha_by_Country_full_sort_by_faith.pdf"), device = cairo_pdf, 
         plot = g, width = 14, height = 10, units = "in", dpi = 300) 

for (a in metric){
  wwdat <- wdat %>% filter(Metrics == a)
  wsummary <- alpha_Country_summary %>% filter(Metrics == a) %>%
    arrange(Med)
  ord = wsummary %>% pull(Country)
  wwdat$Country <- factor(wwdat$Country, levels = ord, ordered = T)
  g <- ggplot(wwdat, aes(Country, value)) + 
    geom_boxplot(aes(color = Country, fill = Country),alpha = 0.7,  outlier.alpha = 0) + 
    geom_point(aes(color = Country), position = position_jitterdodge()) + 
    geom_text(data = wsummary, 
              aes(x =  Country, y = 1.08 * Max, label = KW_group)) + 
    scale_color_manual(values = Country_color, aesthetics = c("color","fill")) + 
    scale_x_discrete(labels=Country_labels) + 
    labs(x = "", y = a) + 
    theme_bw() + theme(#aspect.ratio = 0.8,
                     legend.position="none",
                     panel.background = element_rect(fill = NA),
                     strip.text = element_text(size=12,color="black",face='bold'),
                     axis.title = element_text(size=12,color="black",face='bold'),
                     axis.text = element_text(size=12,color="black",face='bold'),
                     axis.text.x = element_markdown(size=12,face='bold',angle=90,vjust = 0.5, hjust = 1),
                     axis.text.y = element_text(size=12,color="black",face='bold'),
                     legend.text = element_text(size=12,color="black",face='bold'),
                     legend.title = element_text(size=12,color="black",face='bold'),
                     title = element_text(size=12,color="black",face='bold'))
  ggsave(filename = paste0(temp_out, "alpha_by_Country_single_", a, "_ordered.pdf"), device = cairo_pdf, 
         plot = g, width = 7, height = 5, units = "in", dpi = 300) 
}


# Continent

alpha_Continent_grp <- map_dfr(metric, function(a){
  res <- comp_kw_aov(wdat = dat, x = "Continent", y = a)
  res$grp$Metrics = a
  res$grp
})
write.csv(alpha_Continent_grp, row.names = FALSE,
          file = paste0(temp_out,"alpha_by_Continent_kw_aov_grp.csv"))
alpha_Continent_pvalue <- map_dfr(metric, function(a){
  res <- comp_kw_aov(wdat = dat, x = "Continent", y = a)
  res$comp$Metrics = a
  res$comp
})
write.csv(alpha_Continent_pvalue, row.names = FALSE,
          file = paste0(temp_out,"alpha_by_Continent_kw_aov_pvalue.csv"))  

alpha_Continent_summary <- dat %>% dplyr::select(Faith_PD:Pielou_evenness, Continent) %>% 
  group_by(Continent) %>% 
  summarise_all(my_summarize) %>% 
  ungroup() %>%
  pivot_longer(-Continent,
               names_to = "Metrics",
               values_to = "value") %>% 
  unnest(cols = value) %>% 
  left_join(alpha_Continent_grp, by = c("Continent"="Var", "Metrics"="Metrics"))

wdat <- dat %>% 
  dplyr::select(SampleID, Continent, Faith_PD:Pielou_evenness) %>% 
  pivot_longer(Faith_PD:Pielou_evenness, names_to = "Metrics", values_to = "value") 

g <- ggplot(wdat, aes(Continent, value)) + 
  geom_boxplot(aes(color = Continent, fill = Continent),alpha = 0.7,  outlier.alpha = 0) + 
  geom_point(aes(color = Continent), position = position_jitterdodge()) + 
  geom_text(data = alpha_Continent_summary, 
            aes(x =  Continent, y = 1.05 * Max, label = KW_group)) + 
  scale_color_manual(values = Continent_color, aesthetics = c("color","fill")) + 
  #scale_x_discrete(labels=country_labels) + 
  labs(x = "", y = "") +
  facet_wrap(~Metrics, nrow = 2, scales = "free") +
  theme_bw() + theme(#aspect.ratio = 0.8,
                     legend.position="none",
                     panel.background = element_rect(fill = NA),
                     strip.text = element_text(size=12,color="black",face='bold'),
                     axis.title = element_text(size=12,color="black",face='bold'),
                     axis.text = element_text(size=12,color="black",face='bold'),
                     axis.text.x = element_markdown(size=12, face='bold',vjust = 0.5, hjust = 0.5),
                     axis.text.y = element_text(size=12,color="black",face='bold'),
                     legend.text = element_text(size=12,color="black",face='bold'),
                     legend.title = element_text(size=12,color="black",face='bold'),
                     title = element_text(size=12,color="black",face='bold'))
ggsave(filename = paste0(temp_out, "alpha_by_Continent_full.pdf"), device = cairo_pdf, 
         plot = g, width = 14, height = 10, units = "in", dpi = 300) 

```

## beta
### function
```{r}
library(usedist)
calcOmega2_dm <- function(x) {
    # Computes the effect size omega^2 parital using the output from adonis test
    # Args:
    #   x: adonis output
    # Returns:
    #   A dataframe with calculated effect size omega^2 partial added to original dataframe
    require(dplyr)
    N_t = x["Total", ]$Df + 1
    MSe = x["Residual", ]$SumOfSqs/x["Residual", ]$Df
    out = x %>% as.data.frame %>% rownames_to_column(var = "Variable") %>% mutate(Omega2_partial = ifelse(is.na(`F`), NA, (SumOfSqs - Df * MSe)/(SumOfSqs + (N_t - Df) * MSe)))
    return(out)
}
```

### stat
```{r}
temp_out <- "~/Library/CloudStorage/Dropbox/rutgers/20220606_RUN41_milk/Data/output/global/beta/"
for(dd in c("uu","wu","bray","jaccard")){
  wdist <- get(paste0("DM_",dd, "_global"))
  wmeta = meta_global %>% filter(SampleID %in% labels(wdist))
  wdist <- dist_subset(wdist, wmeta$SampleID) 
  print(dd)
  ## Country
  disper <- betadisper(wdist, wmeta$Country)
  disper_ova <- anova(disper)
  disper_HSD <- TukeyHSD(disper)
  write.csv(disper_ova, file = paste0(temp_out,"disper_anova_", dd, "_Country.csv"), quote = F)
  write.csv(disper_HSD$group, file = paste0(temp_out,"disper_HSD_", dd, "_Country.csv"), quote = F)
  
  per <- adonis2(wdist ~ Country, data = wmeta, by = "margin")
  res <-  calcOmega2_dm(per)
  write.csv(res, file = paste0(temp_out,"adonis_test_", dd, "_Country.csv"), quote = F, row.names = F)
  
  ## Continent
  disper <- betadisper(wdist, wmeta$Continent)
  disper_ova <- anova(disper)
  disper_HSD <- TukeyHSD(disper)
  write.csv(disper_ova, file = paste0(temp_out,"disper_anova_", dd, "_Continent.csv"), quote = F)
  write.csv(disper_HSD$group, file = paste0(temp_out,"disper_HSD_", dd, "_Continent.csv"), quote = F)
  
  per <- adonis2(wdist ~ Continent, data = wmeta, by = "margin")
  res <-calcOmega2_dm(per)
  write.csv(res, file = paste0(temp_out,"adonis_test_", dd, "_Continent.csv"), quote = F, row.names = F)
}
```

### PCoA
```{r}
for(dd in c("uu","wu","bray","jaccard")){
  wdist <- get(paste0("DM_",dd, "_global"))
  wmeta = meta_global %>% filter(SampleID %in% labels(wdist))
  wdist <- dist_subset(wdist, wmeta$SampleID) 
  
  ## PCoA
  wpcoa <- pcoa(wdist)
  varPC1 <- round(wpcoa$values$Relative_eig[1]*100, 2)
  varPC2 <- round(wpcoa$values$Relative_eig[2]*100, 2)
  x_lab <- paste0("PC1 (", varPC1, "%)")
  y_lab <- paste0("PC2 (", varPC2, "%)")
  wdat_pcoa <- merge(wpcoa$vectors[,1:2], 
                    wmeta, by.x = 0, by.y = "SampleID", all.x = T) %>% 
    rename(PC1 = Axis.1, PC2 = Axis.2)
  
  ## Country
  wdat_center <- wdat_pcoa %>% group_by(Country) %>% 
    summarise(across(starts_with("PC"), mean)) %>% dplyr::select(-PCRConc) %>% 
    left_join(wmeta %>% dplyr::select(Country, Continent) %>% unique(),by = "Country")
  wdat <- wdat_pcoa %>% left_join(wdat_center %>% transmute(PC1.c = PC1, PC2.c = PC2, Country), by = "Country")
  
  g_tab <- read.csv(paste0(temp_out,"adonis_test_", dd, "_Country.csv")) %>% 
    filter(!is.na(Omega2_partial)) %>% 
    transmute(Name = Variable, Df = Df, SumOfSqs = round(SumOfSqs, 3),
              R2 = round(R2, 3), `F` = round(`F`, 3), Pvalue = round(`Pr..F.`,3),
              Omega2_partial = round(Omega2_partial,3)) %>% column_to_rownames(var = "Name")
  ### points
  g <- ggplot(wdat, aes(x = PC1, y = PC2, color = Country)) + 
      geom_point(size = 2) + 
      scale_color_manual(values = Country_color) + 
      labs(x = x_lab, y = y_lab, title = "") +
      theme_bw() + theme(#aspect.ratio = 1,
                           panel.background = element_rect(fill = NA),
                           strip.text = element_text(size=12,color="black",face='bold'),
                           axis.title = element_text(size=12,color="black",face='bold'),
                           axis.text = element_text(size=12,color="black",face='bold'),
                           axis.text.x = element_text(size=12,color="black",face='bold'),
                           axis.text.y = element_text(size=12,color="black",face='bold'),
                           legend.text = element_text(size=12,color="black",face='bold'),
                           legend.title = element_text(size=12,color="black",face='bold'),
                           title = element_text(size=12,color="black",face='bold'))  
  xmin <- ggplot_build(g)$layout$panel_scales_x[[1]]$range$range[1]
  xmax <- ggplot_build(g)$layout$panel_scales_x[[1]]$range$range[2]
  ymin <- ggplot_build(g)$layout$panel_scales_y[[1]]$range$range[1]
  ymax <- ggplot_build(g)$layout$panel_scales_y[[1]]$range$range[2]
  g = g + ylim(c(ymin - (ymax - ymin)/5, ymax)) +
    annotation_custom(grob = tableGrob(g_tab, theme = ttheme_minimal(base_size = 10)),
                      xmin = xmin, xmax = xmax,
                      ymin = ymin - (ymax - ymin)/5, ymax = ymin)   
  ggsave(filename = paste0(temp_out,"PCoA_",dd,"_by_Country.pdf"), device = cairo_pdf, 
           plot = g, width = 7, height = 5, units = "in", dpi = 300)  
  ### center
  g <- ggplot(wdat_center, aes(x = PC1, y = PC2, color = Continent)) + 
    geom_point(data = wdat, aes(x = PC1, y = PC2, color = Continent), size = 1, alpha = 0.5) + 
    geom_segment(data = wdat, aes(x = PC1, y = PC2, xend = PC1.c, yend = PC2.c), size = 0.2, alpha = 0.5) + 
    geom_point(size = 4,shape = 21, color = "black", aes(fill = Continent)) + 
    geom_text_repel(aes(label = Country), color = "black") + 
    scale_color_manual(values = Continent_color, aesthetics = c("color","fill")) + 
    labs(x = x_lab, y = y_lab, title = "") +
    theme_bw() + theme(#aspect.ratio = 1,
      panel.background = element_rect(fill = NA),
      strip.text = element_text(size=12,color="black",face='bold'),
      axis.title = element_text(size=12,color="black",face='bold'),
      axis.text = element_text(size=12,color="black",face='bold'),
      axis.text.x = element_text(size=12,color="black",face='bold'),
      axis.text.y = element_text(size=12,color="black",face='bold'),
      legend.text = element_text(size=12,color="black",face='bold'),
      legend.title = element_text(size=12,color="black",face='bold'),
      title = element_text(size=12,color="black",face='bold')) 
  xmin <- ggplot_build(g)$layout$panel_scales_x[[1]]$range$range[1]
  xmax <- ggplot_build(g)$layout$panel_scales_x[[1]]$range$range[2]
  ymin <- ggplot_build(g)$layout$panel_scales_y[[1]]$range$range[1]
  ymax <- ggplot_build(g)$layout$panel_scales_y[[1]]$range$range[2]
  g = g + ylim(c(ymin - (ymax - ymin)/5, ymax)) +
    annotation_custom(grob = tableGrob(g_tab, theme = ttheme_minimal(base_size = 10)),
                      xmin = xmin, xmax = xmax,
                      ymin = ymin - (ymax - ymin)/5, ymax = ymin)    
  ggsave(filename = paste0(temp_out,"PCoA_",dd,"_by_Country_center.pdf"), device = cairo_pdf, 
           plot = g, width = 7, height = 5, units = "in", dpi = 300) 
  
  ## Continent
  wdat_center2 <- wdat_pcoa %>% group_by(Continent) %>% 
    summarise(across(starts_with("PC"), mean)) %>% dplyr::select(-PCRConc) %>% 
    left_join(wmeta %>% dplyr::select(Continent) %>% unique(),by = "Continent")
  wdat2 <- wdat_pcoa %>% left_join(wdat_center2 %>% transmute(PC1.c = PC1, PC2.c = PC2, Continent), by = "Continent")
  
  g_tab <- read.csv(paste0(temp_out,"adonis_test_", dd, "_Continent.csv")) %>% 
    filter(!is.na(Omega2_partial)) %>% 
    transmute(Name = Variable, Df = Df, SumOfSqs = round(SumOfSqs, 3),
              R2 = round(R2, 3), `F` = round(`F`, 3), Pvalue = round(`Pr..F.`,3),
              Omega2_partial = round(Omega2_partial,3)) %>% column_to_rownames(var = "Name")
  
  g <- ggplot(wdat_center2, aes(x = PC1, y = PC2, color = Continent)) + 
    geom_point(data = wdat2, aes(x = PC1, y = PC2, color = Continent), size = 1, alpha = 0.5) + 
    geom_segment(data = wdat2, aes(x = PC1, y = PC2, xend = PC1.c, yend = PC2.c), size = 0.2, alpha = 0.5) + 
    geom_point(size = 4, shape = 21, color = "black", aes(fill = Continent)) + 
    geom_text_repel(aes(label = Continent), color = "black") + 
    scale_color_manual(values = Continent_color, aesthetics = c("color","fill")) + 
    #stat_ellipse(data = wdat2, aes(x = PC1, y = PC2, color = Continent)) + 
    labs(x = x_lab, y = y_lab, title = "") +
    theme_bw() + theme(#aspect.ratio = 1,
                           panel.background = element_rect(fill = NA),
                           strip.text = element_text(size=12,color="black",face='bold'),
                           axis.title = element_text(size=12,color="black",face='bold'),
                           axis.text = element_text(size=12,color="black",face='bold'),
                           axis.text.x = element_text(size=12,color="black",face='bold'),
                           axis.text.y = element_text(size=12,color="black",face='bold'),
                           legend.text = element_text(size=12,color="black",face='bold'),
                           legend.title = element_text(size=12,color="black",face='bold'),
                           title = element_text(size=12,color="black",face='bold'))
  xmin <- ggplot_build(g)$layout$panel_scales_x[[1]]$range$range[1]
  xmax <- ggplot_build(g)$layout$panel_scales_x[[1]]$range$range[2]
  ymin <- ggplot_build(g)$layout$panel_scales_y[[1]]$range$range[1]
  ymax <- ggplot_build(g)$layout$panel_scales_y[[1]]$range$range[2]
  g = g + ylim(c(ymin - (ymax - ymin)/5, ymax)) +
    annotation_custom(grob = tableGrob(g_tab, theme = ttheme_minimal(base_size = 10)),
                      xmin = xmin, xmax = xmax,
                      ymin = ymin - (ymax - ymin)/5, ymax = ymin)   
  ggsave(filename = paste0(temp_out,"PCoA_",dd,"_by_Continent_center.pdf"), device = cairo_pdf, 
           plot = g, width = 7, height = 5, units = "in", dpi = 300)  
}
```




